name: CI

on:
  push:
    branches: [ !main ]
  pull_request:
    branches: [ "main" ]
    types: [closed, opened]
  workflow_dispatch:
    inputs:
      run_job1:
        description: Run Job 1
        type: boolean
        default: false
      run_job2:
        description: Run Job 2
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: dump-info
        run: |
          echo 'inputs: ${{ toJSON(inputs) }}'
          echo 'github: ${{ toJSON(github) }}'
          echo 'push: "${{ (github.event.pusher && 'true') || 'false' }}"'
          echo 'gjob1: "${{ (github.event.inputs.run_job1) && 'true' || 'false' }}"'
          echo 'gjob2: "${{ (github.event.inputs.run_job2) && 'true' || 'false' }}"'
          echo 'ijob1: "${{ (inputs.run_job1) && 'true' || 'false' }}"'
          echo 'ijob2: "${{ (inputs.run_job2) && 'true' || 'false' }}"'
          echo 'merged: "${{ github.event.pull_request.merged }}"'
      - name: Input Job 1
        if: ${{ inputs.run_job1 }}
        run: echo input JOB1!!!

      - name: Input Job 2
        if: ${{ inputs.run_job2 }}
        run: echo input JOB2!!!
      
      - name: Pusher Job
        if: ${{ github.evnet.pusher }}
        run: echo puhser!!!
      
      - name: merge Job
        if: ${{ github.evnet.pull_request.merged }}
        run: echo puhser!!!
