name: CI

on:
  push:
    branches-ignore: [ main ]
  pull_request:
    branches: [ "main" ]
    types: [closed, opened]
  workflow_dispatch:
    inputs:
      run_job1:
        description: Run Job 1
        type: boolean
        default: false
      run_job2:
        description: Run Job 2
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: dump-info
        run: |
          echo 'inputs: ${{ toJSON(inputs) }}'
          echo 'github: ${{ toJSON(github) }}'
          echo 'push: "${{ (github.event.pusher && 'true') || 'false' }}"'
          echo 'gjob1: "${{ (github.event.inputs.run_job1) && 'true' || 'false' }}"'
          echo 'gjob2: "${{ (github.event.inputs.run_job2) && 'true' || 'false' }}"'
          echo 'ijob1: "${{ (inputs.run_job1) && 'true' || 'false' }}"'
          echo 'ijob2: "${{ (inputs.run_job2) && 'true' || 'false' }}"'
          echo 'merged: "${{ github.event.pull_request.merged }}"'
      - name: Input Job 1
        if: ${{ inputs.run_job1 }}
        run: echo input JOB1!!!

      - name: Input Job 2
        if: ${{ inputs.run_job2 }}
        run: echo input JOB2!!!
      
      - name: Pusher Job
        if: ${{ github.evnet.pusher }}
        run: echo puhser!!!
      
      - name: merge Job
        if: ${{ github.evnet.pull_request.merged }}
        run: echo puhser!!!
      - name: check for changes
        id: check-for-changes
        uses: tj-actions/changed-files@v46.0.5
        with:
          files_yaml: |
            .github/**
      - name: dump changes
        if: steps.changed-files-yaml.outputs.doc_any_changed == 'true'
        env:
          DOC_ALL_CHANGED_FILES: ${{ steps.changed-files-yaml.outputs.doc_all_changed_files }}
        run: |
          echo "One or more workflow file(s) has changed."
          echo "List all the files that have changed: $DOC_ALL_CHANGED_FILES"
