name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      run_job1:
        description: Run Job 1
        type: boolean
        default: false
      run_job2:
        description: Run Job 2
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: dump-info
        run: |
          echo 'inputs: ${{ toJSON(inputs) }}'
          echo 'github: ${{ toJSON(github) }}'
          echo 'push: "${{ (github.event.pusher && 'true') || 'false' }}"'
          echo 'gjob1: "${{ (github.event.inputs.run_job1) && 'true' || 'false' }}"'
          echo 'gjob2: "${{ (github.event.inputs.run_job2) && 'true' || 'false' }}"'
          echo 'ijob1: "${{ (inputs.run_job1) && 'true' || 'false' }}"'
          echo 'ijob2: "${{ (inputs.run_job2) && 'true' || 'false' }}"'
          echo 'merged: "${{ github.event.pull_request.merged }}"'
      - name: Job 1
        if: ${{ github.event.pusher || inputs.run_job1 }}
        run: echo JOB1!!!

      # Runs a set of commands using the runners shell
      - name: Job 2
        if: ${{ github.event.pusher || inputs.run_job2 }}
        run: echo JOB2!!!
